version: '3.8'

services:
    app:
        build: .
        ports:
            - "8005:80"
        volumes:
            - .:/var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html
